(() => {
  const endpoint='https://api.arteari.com.br/catalog';
  const grid=document.querySelector('.products-grid');
  if(!grid)return;
  const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
  const quoteLabel='Vamos criar seu orçamento?';
  const overlay=document.querySelector('#lightbox-overlay'),lbImg=document.querySelector('#lb-main-img'),lbTitle=document.querySelector('#lightbox-title'),lbPrice=document.querySelector('#lightbox-price'),lbWpp=document.querySelector('#lightbox-wpp'),lbThumbs=document.querySelector('#lightbox-thumbs'),lbCounter=document.querySelector('#lightbox-counter');
  function show(card){const images=JSON.parse(card.dataset.images||'[]');if(!images.length||!overlay)return;let index=0;const render=()=>{lbImg.src=images[index];lbImg.alt=card.dataset.title;lbTitle.textContent=card.dataset.title;lbPrice.textContent=card.dataset.price;lbPrice.classList.toggle('quote-price',card.dataset.price===quoteLabel);lbWpp.href=`https://wa.me/5524993154334?text=${card.dataset.wpp}`;lbCounter.textContent=`${index+1} / ${images.length}`;lbThumbs.innerHTML=images.map((image,item)=>`<button class="lb-thumb ${item===index?'active':''}" type="button"><img src="${escape(image)}" alt=""></button>`).join('');$$('.lb-thumb',lbThumbs).forEach((button,item)=>button.onclick=()=>{index=item;render()})};render();overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const attach=(card)=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label','Ver galeria de '+card.dataset.title);card.addEventListener('click',()=>show(card));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();show(card)}});};
  const cardFor=product=>{const images=Array.isArray(product.images)?product.images:[],image=images[0]||'assets/atelier-icons/materials-vignette-icon.png',message=encodeURIComponent(product.whatsapp_message||`Tenho interesse em ${product.title}`),showPrice=product.show_price===1&&product.price_cents!=null,price=showPrice?money(product.price_cents):quoteLabel;const card=document.createElement('div');card.className='product-card';card.dataset.cat=product.category_slug;card.dataset.title=product.title;card.dataset.price=price;card.dataset.wpp=message;card.dataset.images=JSON.stringify(images);card.innerHTML=`<div class="product-img-wrap"><img src="${escape(image)}" alt="${escape(product.title)}" loading="lazy"><span class="product-gallery-hint">ver galeria</span>${product.badge?`<span class="product-badge">${escape(product.badge)}</span>`:''}</div><div class="product-info"><span class="product-cat">${escape(product.category_name)}</span><div class="product-name">${escape(product.title)}</div><div class="product-price">${showPrice?'<small>a partir de</small><br>':''}${escape(price)}</div><a class="product-wpp" href="https://wa.me/5524993154334?text=${message}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()">Pedir pelo WhatsApp</a></div>`;attach(card);return card};
  async function sync(){try{const response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw Error();const data=await response.json();if(!Array.isArray(data.products)||!data.products.length)throw Error();grid.innerHTML='';data.products.forEach(product=>grid.append(cardFor(product)));document.querySelectorAll('.cat-btn').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;document.querySelectorAll('.product-card').forEach(card=>card.classList.toggle('hidden',filter!=='all'&&card.dataset.cat!==filter))}));}catch{/* O catálogo estático do repositório continua como fallback seguro. */}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',sync,{once:true});else sync();
})();
